// <auto-generated />
using ContatosInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContatosInfrastructure.Migrations
{
    [DbContext(typeof(ContatosApplicationContext))]
    [Migration("20210330010059_Mestre detalhe")]
    partial class Mestredetalhe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContatosDomain.Models.Contato", b =>
                {
                    b.Property<string>("ContatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContatoId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("ContatosDomain.Models.ContatoNumero", b =>
                {
                    b.Property<string>("ContatoNumeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContatoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("ContatoNumeroId");

                    b.HasIndex("ContatoId");

                    b.ToTable("ContatoNumero");
                });

            modelBuilder.Entity("ContatosDomain.Models.ContatoNumero", b =>
                {
                    b.HasOne("ContatosDomain.Models.Contato", null)
                        .WithMany("Numeros")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContatosDomain.Models.Contato", b =>
                {
                    b.Navigation("Numeros");
                });
#pragma warning restore 612, 618
        }
    }
}
